FROM jenkins/jenkins:lts-jdk17

# Define environment variables
ENV JENKINS_HOME=/home/jenkins \
    JENKINS_MOUNT_POINT=/mnt/jenkins \
    JENKINS_BACKUP=/mnt/jenkins/backups \
    JENKINS_SCRIPTS=/data/jenkins/scripts

USER root

# Update and install required packages in a single step
RUN apt-get update \
    && apt-get install -y vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy executable scripts
COPY jenkins-master/executable ${JENKINS_SCRIPTS}
