apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: [[APP_NAMESPACE]]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: [[APP_IMAGE]]
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: [[APP_NAMESPACE]]
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort